version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:qweqwe@psql:5432/js
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp-relay.sendinblue.com
      - MAIL_PORT=587
      - MAIL_USERNAME=be.hkm.plexus@gmail.com
      - MAIL_PASSWORD=m0RQ53kFNjd91ZnL
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=YourApp
      - SENDINBLUE_API_KEY=YOUR_SENDINBLUE_API_KEY
      - APP_NAME=YourApp
      - JWT_SECRET=c24a752e1491bd7c5c4978fe048ad9e2853322247edcf764d8ac46948e4137c9
    depends_on:
      - db
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=qweqwe
   
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  db:
    container_name: "psql"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: js
      POSTGRES_USER: postgres
      POSTGRES_PASS: qweqwe
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
